name: Update Data Script
on:
  schedule:
    - cron: '0 6 * * *'  # Fixed syntax
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }} 
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install nest_asyncio asyncio pylitterbot pandas
      
      # Debug step
      - name: Debug environment variables
        run: |
          echo "Username variable exists: ${{ secrets.LITTER_ROBOT_USERNAME != '' }}"
          echo "Password variable exists: ${{ secrets.LITTER_ROBOT_PASSWORD != '' }}"
          echo "Username length: ${#LITTER_ROBOT_USERNAME}"
          echo "Password length: ${#LITTER_ROBOT_PASSWORD}"
        env:
          LITTER_ROBOT_USERNAME: ${{ secrets.LITTER_ROBOT_USERNAME }}
          LITTER_ROBOT_PASSWORD: ${{ secrets.LITTER_ROBOT_PASSWORD }}
      
      - name: Run update script
        run: python update_yesterday_data_script.py
        env:
          LITTER_ROBOT_USERNAME: ${{ secrets.LITTER_ROBOT_USERNAME }}
          LITTER_ROBOT_PASSWORD: ${{ secrets.LITTER_ROBOT_PASSWORD }}
      
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add master_lr4_practice.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data via GitHub Actions"
          git push
